FROM node:22-alpine

WORKDIR /app

# Instalar dependências básicas
RUN apk add --no-cache bash curl

# Copiar arquivos de dependência
COPY ./package.json ./package-lock.json ./

# Instalar dependências usando npm
RUN npm install --production

# Copiar o código do serviço REST
COPY ./app/api/rest ./app/api/rest

# Garantir acesso ao diretório hooks
RUN mkdir -p /app/hooks && chmod 777 /app/hooks

# Expor porta
EXPOSE 5000

# Iniciar o serviço
CMD ["node", "app/api/rest/route.js"]